### ISSUE TITLE
[MAPPING] Master Checklist

### ISSUE THREAD

**Issue by EliteMasterEric** [EliteMasterEric/Teyvat.moe#88]
This issue will act as the massive primary checklist to consolidate and summarize progress. Conversation should be directed to other linked issues.

# Chest
This includes chests and trials that grant them.

Click for [more information and discussion on these features](https://github.com/GenshinMap/genshinmap.github.io/issues/10).

The current chest data set is extremely messy, it was partially imported from yuanshen.site by manually inspecting the comment image and sorting based on perceived rarity. Since these images were often blurry and even used some closed beta test graphics, it is highly encouraged and appreciated for users to aid in the chest mapping process.

Note that to maintain the legacy import functionality, existing internal IDs should not be modified, and additionally newly added chests should use a high offset like `2000`.

## Mondstadt
- [x] Luxurious Chest (Mondstadt)
  - These have been fully verified with screenshots and descriptions by @MasterEric.
- [ ] Precious Chests (Mondstadt)
  - These certainly need work. Many entries are missing and others need new screenshots.
- [ ] Exquisite Chests (Mondstadt)
  - These certainly need work. Many entries are missing and others need new screenshots. Descriptions are not needed for chests without challenges.
- [ ] Common Chests (Mondstadt)
  - These are incredibly messy. There are many chests here that simply don't exist, while others are missing images, or use images from so long ago the chest graphic looks completely different. Manual review and inspections, while time consuming, are necessary and greatly appreciated.
  - [ ] Markers
  - [ ] Media
  - [ ] Descriptions (not needed for most common chests)
- [X] Shrines (Mondstadt)
  - Due to their specific requirements, Shrines have their own category. These have been fully verified with screenshots and descriptions by @MasterEric.
- [ ] Seelies (Mondstadt)
  - Seelies should be included in their own separate category, since they are involved with special achievements. Like most of the other chest categories, this is really messy and would appreciate some cleanup.
- [ ] Time Trials (Mondstadt)
  - Time Trials should be included in their own separate category, since they are involved with special achievements. Like most of the other chest categories, this is really messy and would appreciate some cleanup.
## Liyue
- [x] Luxurious Chest (Liyue)
  - These have been fully verified with screenshots and descriptions by @MasterEric.
- [ ] Precious Chests (Liyue)
  - These certainly need work. Many entries are missing and others need new screenshots.
- [ ] Exquisite Chests (Liyue)
  - These certainly need work. Many entries are missing and others need new screenshots. Descriptions are not needed for chests without challenges.
- [ ] Common Chests (Liyue)
  - These are incredibly messy. There are many chests here that simply don't exist, while others are missing images, or use images from so long ago the chest graphic looks completely different. Manual review and inspections, while time consuming, are necessary and greatly appreciated.
- [X] Shrines (Liyue)
  - Due to their specific requirements, Shrines have their own category. These have been fully verified with screenshots and descriptions by @MasterEric.
- [ ] Seelies (Liyue)
  - Seelies should be included in their own separate category, since they are involved with special achievements. Like most of the other chest categories, this is really messy and would appreciate some cleanup.
- [ ] Time Trials (Liyue)
  - Time Trials should be included in their own separate category, since they are involved with special achievements. Like most of the other chest categories, this is really messy and would appreciate some cleanup.
- [ ] Dandy
  - The time trial NPC in several places in Liyue. Provides three chests for different races.
# Monster
This includes any normal or Elite mobs found in the world.

Click for [more information and discussion on these features](https://github.com/GenshinMap/genshinmap.github.io/issues/36).

# Nature
This includes any meat, plants, or insects found in the world.

Click for [more information and discussion on these features](https://github.com/GenshinMap/genshinmap.github.io/issues/13).

# Ore
This includes any rocks or minerals found in the world.

Click for [more information and discussion on these features](https://github.com/GenshinMap/genshinmap.github.io/issues/80).

## Mondstadt
- [ ] [Magical Crystal Chunk (Mondstadt)](https://github.com/GenshinMap/genshinmap.github.io/issues/89)
- [ ] Crystal Chunk (Mondstadt)
  - Map imported from yuanshen.site. May be incomplete, requires verification and preferably media.
  - [ ] Markers
  - [ ] Media
- [ ] Electro Crystal (Mondstadt)
  - Map imported from yuanshen.site. May be incomplete, requires verification and preferably media.
  - [ ] Markers
  - [ ] Media
- [ ] Iron Chunk (Mondstadt)
  - Map imported from yuanshen.site. May be incomplete, requires verification and preferably media.
  - [ ] Markers
  - [ ] Media
- [ ] White Iron Chunk (Mondstadt)
  - Map imported from yuanshen.site. May be incomplete, requires verification and preferably media.
  - [ ] Markers
  - [ ] Media
## Liyue
- [ ] [Magical Crystal Chunk (Liyue)](https://github.com/GenshinMap/genshinmap.github.io/issues/89)
  - New to 1.1. Click the link for more info about mapping this feature.
- [ ] Crystal Chunk (Mondstadt)
  - Map imported from yuanshen.site. May be incomplete, requires verification and preferably media.
  - [ ] Markers
  - [ ] Media
- [ ] Electro Crystal (Mondstadt)
  - Map imported from yuanshen.site. May be incomplete, requires verification and preferably media.
  - [ ] Markers
  - [ ] Media
- [ ] Iron Chunk (Mondstadt)
  - Map imported from yuanshen.site. May be incomplete, requires verification and preferably media.
  - [ ] Markers
  - [ ] Media
- [ ] White Iron Chunk (Mondstadt)
  - Map imported from yuanshen.site. May be incomplete, requires verification and preferably media.
  - [ ] Markers
  - [ ] Media
- [ ] Cor Lapis
  - Map imported from yuanshen.site. May be incomplete, requires verification and preferably media.
  - [ ] Markers
  - [ ] Media
- [ ] Noctilucous Jade
  - Map imported from yuanshen.site. May be incomplete, requires verification and preferably media.
  - [ ] Markers
  - [ ] Media
# Special
Special markers include teleportation points (such as domains and statues), viewpoints, and of course the Oculus.
## Mondstadt
- [ ] Anemoculus
  - All locations are done, but there are improvements to be made in popup content.
  - [x] Markers
  - [ ] Media
  - [ ] Description
- [x] Domain (Mondstadt)
  - Media simply uses the thumbnail image. Description specifies available drops and how to access (if complicated).
  - [x] Markers
  - [x] Media
  - [x] Description
- [x] Statue (Mondstadt)
  - Media uses ingame screenshots.
  - [x] Markers
  - [x] Media
- [x] Teleporter (Mondstadt)
  - Media uses ingame screenshots from @MasterEric.
  - [x] Markers
  - [x] Media
- [x] Viewpoint (Mondstadt)
  - Title and media use the ingame archive display.
  - [x] Markers
  - [x] Media
## Liyue
- [ ] Geoculus
  - All locations are done, but there are improvements to be made in popup content.
  - [x] Markers
  - [ ] Media
  - [ ] Description
- [x] Domain (Liyue)
  - Media simply uses the thumbnail image. Description specifies available drops and how to access (if complicated).
  - [x] Markers
  - [x] Media
  - [x] Description
- [x] Statue (Liyue)
  - Media uses ingame screenshots from @MasterEric.
  - [x] Markers
  - [x] Media
- [x] Teleporter (Liyue)
  - Media uses ingame screenshots from @MasterEric.
  - [x] Markers
  - [x] Media
- [x] Viewpoint (Liyue)
  - Title and media use the ingame archive display.
  - [x] Markers
  - [x] Media
# Boss
Includes World Bosses and Weekly Bosses. Only markers are necessary for bosses.
## Mondstadt
- [x] Anemo Hypostasis
  - [x] Marker
- [x] Electro Hypostasis
  - [x] Marker
- [x] Cryo Regisvine
  - [x] Marker
- [x] Andrius
  - [x] Marker
- [x] Dvalin
  - [x] Marker
## Liyue
- [x] Geo Hypostasis
  - [x] Marker
- [x] Pyro Regisvine
  - [x] Marker
- [x] Oceanid
  - [x] Marker
- [x] Childe
  - [x] Marker
# Event
- [x] Meteorite Shards (Mondstadt)
  - Markers, routes, English descriptions, and screenshots provided by @MasterEric.
  - [x] Markers
  - [x] Routes
  - [x] Descriptions
  - [x] Media
- [x] Meteorite Shards (Liyue)
  - Markers, routes, English descriptions, and screenshots provided by @MasterEric.
  - [x] Markers
  - [x] Routes
  - [x] Descriptions
  - [x] Media

**Comment by EliteMasterEric** [comment]
Moved to #243 .
